### ISSUE TITLE
Plugin not working on Android

### ISSUE THREAD

**Issue by cstranex** [panz3r/react-native-flipper-databases#1]
**Describe the bug**

Trying to run the app after installing leads to:
```com.facebook.flipper.plugins.databases.DatabasesFlipperPlugin cannot be cast to com.facebook.flipper.reactnative.FlipperReactNativeJavaScriptPlugin```

**To Reproduce**

```
yarn add react-native-flipper-databases react-native-flipper --dev
```
Below the creation of the Watermelon Database:
```
if (__DEV__) {
  // Import connectDatabases function
  const connectDatabases = require('react-native-flipper-databases/lib/module').default;

  // Import required DBDrivers
  const WatermelonDBDriver = require('react-native-flipper-databases/lib/module/drivers/watermelondb')
    .default;

  connectDatabases([
    new WatermelonDBDriver(database), // Pass in database definition
  ]);
}
```

**Expected behavior**

App launches

**Smartphone**

- Device: Emulator
- OS: Android

**Comment by panz3r** [comment]
Hi @cstranex ,

Thanks for your feedback, I just opened an issue on the official Flipper repo since it appears to be a "native" issue, let's see how that discussion evolves.

In the meanwhile I suppose I should state that Android is not currently supported by this plugin 😢

**Comment by cstranex** [comment]
Thanks for the feedback @panz3r . Will wait to see what happens from upstream :)

**Comment by panz3r** [comment]
Hi @cstranex ,

The upstream issue has been updated, they are requesting more info to try to reproduce the issue, can you provide them by answering directly to the linked issue?

**Comment by cstranex** [comment]
Hey @panz3r 

Looks like the solution is to remove the following line in `debug/java/.../ReactNativeFlipper.java`:
```java
      client.addPlugin(new InspectorFlipperPlugin(context, DescriptorMapping.withDefaults()));
      client.addPlugin(new ReactFlipperPlugin());
      **// client.addPlugin(new DatabasesFlipperPlugin(context));**
      client.addPlugin(new SharedPreferencesFlipperPlugin(context));
      client.addPlugin(CrashReporterPlugin.getInstance());
```

That will disable the default Flipper Database plugin. Of course with this you will only be able to view the WatermelonDB databases in Flipper.

**Comment by panz3r** [comment]
Hi @cstranex ,

I can confirm that excluding the native plugins does work, I updated the README to explain the required setup on Android.

> Of course with this you will only be able to view the WatermelonDB databases in Flipper.

I think this is not such a big problem in case you are using `WatermelonDB` in a `React Native` app, but of course the change is reversible at any moment (you can choose to disable `react-native-flipper-databases` and re-enable the native plugin if you need to 😬 ).

Thanks again for your feedback and support in fixing this issue.

**Comment by cstranex** [comment]
Yeah, I doubt it would be much of an issue for anyone :)

Always a pleasure, thanks for the useful plugin!
