### ISSUE TITLE
React Native SQLite support

### ISSUE THREAD

**Issue by 3rdp** [panz3r/react-native-flipper-databases#380]
**Is your feature request related to a problem?**

SQLite is a popular local database solution. It's a really bad DX that we can't inspect an SQLite database on iOS.

**Describe the solution you'd like**

A database driver for [`react-native-sqlite-storage`](https://github.com/andpor/react-native-sqlite-storage).

**Describe alternatives you've considered**

There's really no alternatives to that. Well, the built-in Flipper Databases plugin works out of the box on Android and handles SQLite, but on iOS there's no way to achieve that. Although you can just pass a plain object into `connectDatabases` and basically implement all methods of database driver in that object by hand. And call `connectDatabases` only on iOS, of course.

**Comment by panz3r** [comment]
Hi @3rdp ,
Thanks for your feedback and request.

Basic support for `react-native-sqlite-storage` is now available as of version `2.4.0`.

Let me know if it works and if you have more feedbacks about the integration or this library.

**Comment by 3rdp** [comment]
@panz3r sweet, thanks for implementing it! I tried it. It works really well. Great job, very useful feature, my problem is solved. Thank you very much!
